---
title: '?'
author: '?'
date: "2021/3/27"
output: html_document
---
```{r set up, load-packages, include = FALSE}
# Add any additional packages you need to this chunk
library(tidyverse)
library(knitr)
library(dplyr)
library(ggplot2)
library(tibble)
library(openintro)
library(gapminder)

```

```{r load-data, echo = FALSE}
library(readr)
ca <- read_csv(file = "/cloud/project/HuluanAnalysis/ca.csv")
```

```{r Tidy data}
bars <- ca %>%
  select(DEM_GENDER, OP_NMU_EVER, BENZ_NMU_EVER, STIM_NMU_EVER, GABA_NMU_EVER, ILL_USE, DAST_CAT)
  
```





```{r plot a graph to see is there a relation between age and drug abuse}

# filter out the participants of the survey who claimed that they never engaged in durg abuse (five types of drug included)
age <- ca %>%
  filter(
    OP_NMU_EVER == 1|BENZ_NMU_EVER == 1|STIM_NMU_EVER == 1| GABA_NMU_EVER == 1|ILL_USE == 1
  ) %>%
  select(DEM_REGION, DEM_AGE) 

# change the type of variable DEM_REGION
age$DEM_REGION[bars$DEM_REGION == 1] <- 1    
age$DEM_REGION[bars$DEM_REGION == 2] <- 2 
age$DEM_REGION[bars$DEM_REGION == 3] <- 3    
age$DEM_REGION[bars$DEM_REGION == 4] <- 4
age$DEM_REGION <- factor(age$DEM_REGION,    
                          levels=c(1, 2, 3, 4),
                          labels=c("Atlantic", "Québec", "Ontario", "West"))

# create a age categories
attach(age)
age$age_compare[DEM_AGE > 65] <- "Elder"
age$age_compare[DEM_AGE > 35 & DEM_AGE <= 65] <- "Middle Aged"
age$age_compare[DEM_AGE <= 35] <- "Young"
detach(age)

ggplot(age, aes(y = DEM_REGION,
                 fill = age_compare)) +
  geom_bar(position = "fill") +
  labs(x = "Percentage of different age groups who engaged in drug abuse",
       y = "Four regions",
       fill = "Age groups",
       title = "To examine if age has effects on drug abuse"
       )  
```




```{r}
# nmsl
bars$DEM_GENDER[bars$DEM_GENDER == 1] <- 1    #将男性的归类为1
bars$DEM_GENDER[bars$DEM_GENDER == 2] <- 2    #将女性的归类为2
bars$DEM_GENDER <- factor(bars$DEM_GENDER,    #转为factor形式，替换标签
                          levels=c(1, 2),
                          labels=c("Male", "Female"))

# nmsl
bars$OP_NMU_EVER[bars$OP_NMU_EVER == 0] <- 0    #将无的归类为1
bars$OP_NMU_EVER[bars$OP_NMU_EVER == 1] <- 1    #将有的归类为2
bars$OP_NMU_EVER <- factor(bars$OP_NMU_EVER,    #转为factor形式，替换标签
                           levels=c(0, 1),
                           labels=c("None", "Opioids"))


bars$BENZ_NMU_EVER[bars$BENZ_NMU_EVER == 0] <- 0    # ???
bars$BENZ_NMU_EVER[bars$BENZ_NMU_EVER == 1] <- 1    #将男性的归类为1
bars$BENZ_NMU_EVER <- factor(bars$BENZ_NMU_EVER,    #转为factor形式，替换标签
                             levels=c(0,1),
                             labels=c("No","Yes"))
glimpse(bars)


ggplot(bars, aes(y = BENZ_NMU_EVER,
                 fill = DEM_GENDER)) +
  geom_bar(position = "fill") +
  labs(x = "Percentage",
       y = "Drug type: benzodiazepine",
       fill = "Gender%",
       title = "To examine if a certain gender has an inclination for drug abuse"
       )
```

