---
title: '?'
author: '?'
date: "2021/3/27"
output: html_document
---
```{r set up, load-packages, include = FALSE}
# Add any additional packages you need to this chunk
library(tidyverse)
library(broom)
library(knitr)
library(dplyr)
library(ggplot2)
library(tibble)
library(openintro)
library(gapminder)

```


```{r cars}
library(openintro)
loans <- loans_full_schema %>%
  select(loan_amount, interest_rate, term, grade, 
         state, annual_income, homeownership, debt_to_income)
glimpse(loans)

ggplot(loans, aes(y = homeownership,
                  fill = grade)) +
  geom_bar(position = "fill") +
  labs(
    x = "Highest Degree",
    y = "Drug Types",
    fill = "Highest Degree",
    title = "To examine if a certain gender has an inclination for drug abuse",
    subtitle = "with some additional factors"
  )
```


```{r load-data, echo = FALSE}
# load data here, if you like
library(readr)
ca <- read_csv("ca.csv")
```

```{r Tidy data}
library(broom)
bars <- ca %>%
  select(bars$DEM_GENDER == as.factor(DEM_GENDER), 
         OP_NMU_EVER == as.factor(OP_NMU_EVER), 
         BENZ_NMU_EVER = as.factor(BENZ_NMU_EVER), 
         STIM_NMU_EVER = as.factor(STIM_NMU_EVER), 
         GABA_NMU_EVER = as.factor(GABA_NMU_EVER), 
         ILL_USE = as.factor(ILL_USE), 
         DAST_CAT = as.factor(DAST_CAT)) %>%
         group_by(DEM_GENDER)

maps <- ca %>%
  select(DEM_LOCATION)

Drug_abuse <- ca %>%
  select(OP_NMU_EVER, BENZ_NMU_EVER, STIM_NMU_EVER, GABA_NMU_EVER, ILL_USE)
a <- colSums(Drug_abuse[,c(1:5)])
b <- rowSums(Drug_abuse[,c(1:5)])
print(a)
print(b)
  
```

```{r}
ggplot(bars, aes(y = OP_NMU_EVER,
                  fill = DAST_CAT)) +
  geom_bar(position = "fill") +
  labs(
    x = "Proportion",
    y = "Homeownership",
    fill = "Grade",
    title = "Grades of Lending Club loans",
    subtitle = "and homeownership of lendee"
  )
```